### ISSUE TITLE
Not all images show correctly

### ISSUE THREAD

**Issue by PromoFaux** [mattermost/mattermost-mobile#2399]
#### Summary
image attachments with the extension `.jpeg` are not displayed properly

#### Environment Information

- Device Name: Google Pixel 2
- OS Version: Android 9
- Mattermost App Version: 1.14.0
- Mattermost Server Version: 5.4.0

#### Steps to reproduce
Attach an image with the `.jpeg` extension.  Displays fine on desktop browser, but not in mobile client.

#### Expected behavior
All image attachments should be viewable on mobile :)

#### Observed behavior
I'll let the screenshots do the talking!

How it looks on desktop:
![image](https://user-images.githubusercontent.com/1998970/49254673-b904d580-f421-11e8-9a28-aea70022b5fc.png)

How the same thread appears on mobile:
![image](https://user-images.githubusercontent.com/1998970/49254683-c15d1080-f421-11e8-9338-e0e9906fdc26.png)

Clicking on the `.jpeg` image shows this:
![image](https://user-images.githubusercontent.com/1998970/49254715-d639a400-f421-11e8-8b18-ee86d25f9bef.png)

#### Possible fixes
/shrug

**Comment by jacobsalmela** [comment]
I see the exact same on the iOS app.

MM mobile app version: 1.14.0
iOS version: 12.1

**Comment by amyblais** [comment]
Thank you all,

I'm not able to reproduce this on iOS on a mobile app v1.15, server v5.6 version, so it looks like this has been fixed.

If you want to test it out, you can join our [community server here](community.mattermost.com) which is on v5.6. You can sign up for beta testing here to get v1.15: https://play.google.com/apps/testing/com.mattermost.rnbeta.

**Comment by PromoFaux** [comment]
Thanks for looking into it. 

Play store beta version is still 1.14, so unable to confirm :)

**Comment by amyblais** [comment]
Have you had a chance to check if you can reproduce this bug on v1.15?

**Comment by PromoFaux** [comment]
Hi Amy,

Currently have 1.15.1 installed and still seeing this bug.

**Comment by jasonblais** [comment]
Thanks @PromoFaux - would you be open to trying test if it reproduces on our [community server here](https://community.mattermost.com/)? I think you're already a member of the Contributors team.

That'll help us narrow down the potential problem if it doesn't reproduce on community.mattermost.com.

**Comment by amyblais** [comment]
@PromoFaux You could check in the database and see if the mime types are correct for these file types. You can check mime types with
```
SELECT MimeType, count(*) FROM mattermost.FileInfo GROUP BY MimeType ORDER BY 2 DESC;
```

**Comment by PromoFaux** [comment]
@jasonblais 

Just did some tests on your server and on ours, and it appears that it may be server-side rather than mobile related (at this stage, in any case!) Screenshots below:

Your server (note that `jpeg` extension is showing fine both on web client and mobile):

![image](https://user-images.githubusercontent.com/1998970/50728174-c34f7900-111d-11e9-85f7-257951156dbf.png)

![image](https://user-images.githubusercontent.com/1998970/50728176-cc404a80-111d-11e9-9018-26ce4a7c4643.png)

Ours (`jpeg` not displaying correctly):
![image](https://user-images.githubusercontent.com/1998970/50728181-e11cde00-111d-11e9-841b-efaa545a5c16.png)

@amyblais I will get our server admin to check that, I don't have access to the database...

![image](https://user-images.githubusercontent.com/1998970/50728185-e67a2880-111d-11e9-8210-69f2bc417f4c.png)

**Comment by PromoFaux** [comment]
@amyblais I will get our server admin to check that, as I don't have access to the database... paging @dschaper

**Comment by dschaper** [comment]
```
mattermost_db=# SELECT MimeType, count(*) FROM FileInfo GROUP BY MimeType ORDER BY 2 DESC;
                                 mimetype                                  | count
---------------------------------------------------------------------------+-------
 image/png                                                                 |  4863
 image/jpeg                                                                |   998
 text/html; charset=utf-8                                                  |   811
                                                                           |   171
 image/gif                                                                 |   126
 text/plain; charset=utf-8                                                 |   111
 application/pdf                                                           |   111
 application/zip                                                           |    44
 video/mp4                                                                 |    27
 application/x-7z-compressed                                               |     6
 text/x-sh; charset=utf-8                                                  |     6
 application/json                                                          |     5
 application/gzip                                                          |     4
 image/svg+xml                                                             |     3
 video/quicktime                                                           |     2
 application/pgp-keys                                                      |     2
 application/vnd.openxmlformats-officedocument.presentationml.presentation |     2
 application/postscript                                                    |     1
 application/octet-stream                                                  |     1
 application/msword                                                        |     1
 application/x-tar                                                         |     1
 application/vnd.android.package-archive                                   |     1
 text/x-python; charset=utf-8                                              |     1
 application/javascript                                                    |     1
 application/vnd.openxmlformats-officedocument.spreadsheetml.sheet         |     1
(25 rows)
```

**Comment by dschaper** [comment]
`.jpg` seems okay, `.jpeg` shows:

```
2019-01-05T22:14:44.562Z        error   web/context.go:60       File doesn't have a thumbnail image     {"path": "/api/v4/files/yrh7z9mt4i86t88bms343ncizy/thumbnail", "request_id": "hjzp5qfkopdsfbsizmrnj7yxna", "ip_addr": "75.82.xxx.yy", "user_id": "6w7ywtxo1bdajqbima6sd3hhjc", "method": "GET", "err_where": "getFileThumbnail", "http_code": 400, "err_details": "file_id=yrh7z9mt4i86t88bms343ncizy"}
```

**Comment by amyblais** [comment]
Just wanted to give an update that we haven't been able to reproduce this so far, so this seems to be a client side issue.

**Comment by dschaper** [comment]
It's reproducible, upload a file as `file.jpg` and everything is normal. Upload that same exact file as `file.jpeg` and the logs show `error ... File doesn't have a thumbnail image`. Along with the nginx proxy showing the http error.

**Comment by PromoFaux** [comment]
@amyblais Just to confirm this appears to be working now:

Mattermost Version: 5.8.0
App Version 1.16.0 (Build 175)
