### ISSUE TITLE
Sign in with GitLab integration doesn't work

### ISSUE THREAD

**Issue by frol** [mattermost/mattermost-mobile#355]
#### Summary

Mattermost features GitLab integration to sign in with GitLab credentials, but Mattermost RN (beta) on Android seems to lack support this way of authentication.

#### Environment Information

- Device Name: Moto X
- OS Version: Android 5.1
- Mattermost App Version: 1.0 (beta) from March 14, 2017
- Mattermost Server Version: 3.7.0

#### Steps to reproduce

Use Mattermost server configured with GitLab authentication and you won't be able to authenticate due to the fact that the app asks for credentials, but doesn't seem to recognize that it should authenticate with GitLab and just returns with "We couldn't find an account matching your login credentials".

#### Expected behavior

Sign in with GitLab credentials should work.

#### Observed behavior

"We couldn't find an account matching your login credentials"

**Comment by VeraLyu** [comment]
seems Gitlab sso is not available for now:  https://mattermost.atlassian.net/browse/PLT-5886

**Comment by jurgenhaas** [comment]
This is something I would need too before being able to test.

**Comment by Hanzei** [comment]
Fixed with #552

**Comment by nightvisi0n** [comment]
Please don't forget that gitlab has a 2fa feature that maybe needs proper handling.

**Comment by jostyee** [comment]
@nightvisi0n it's working okay with GitLab 2FA auth.

**Comment by ThibaudDauce** [comment]
Is there release planned soon? :-)

Thanks for the feature!

**Comment by d10r** [comment]
The Beta in Play store was updated recently, but unfortunately still doesn't contain this feature.
Is there any place where recent Android builds (e.g. nightlies) can be downloaded?

**Comment by frol** [comment]
@d10r Mattermost Beta application works fine for me! Double-check whether your Mattermost server is 3.10 (it has been released recently).

**Comment by ThibaudDauce** [comment]
@d10r if you're using Gitlab Omnibus, Mattermost 3.10 will be release with Gitlab 9.3 the 22nd

**Comment by kingfisher77** [comment]
After login via Gitlab we just see {"status":"ok"}.

Google Pixel
Mattermost 3.10
Latest Gitlab

Any idea?

**Comment by sedrubal** [comment]
> After login via Gitlab we just see `{"status":"ok"}`.

same here:

- GitLab: 9.3.3
- Mattermost: 3.10.0
- Mattermost RN Beta: 1.0
- Android 7.1.2 (LineageOS) on Nexus 5

**Comment by Berdir** [comment]
Another non-working case here, I see Gitlab as authentication method on the second screen, clicking on that opens a SIngle-Sign-On screen, I see a loading icon for a second and then nothing, just a white screen.

Latest Gitlab Omnibus with LetsEncrypt SSL certificates, Mattermost 2017 Beta 1.0, Android 7.1.2 on a Google Pixel.

**Comment by kingfisher77** [comment]
Check if there is a blank „ „ at the end of the URI. Removing the space solved the login problem for us.

All in all the app is truly beta :)

**Comment by david10sing** [comment]
Same issue as @Berdir on Mattermost 2017 v1.2, Android 7.0, Galaxy S8
