### ISSUE TITLE
Issues with V2 Android app

### ISSUE THREAD

**Issue by samueltootle** [mattermost/mattermost-mobile#7098]
Phone:
OnePlus 6
OS: oxygen OS 11.1.2
Android OS: 11

Mattermost server info: None. I'm not an admin

Issues:
1) Takes a long time to respond when changing chats.
2) consistently sits at the mattermost logo for 5+s
3) issues when attempting to Download non-standard Files (i.e. extensions not recognized by mattermost

Method to reproduce error:
The above are consistent issues on my device. No special circumstances are needed to reproduce the above.

Quality of life issues:
All channels are now mixed and not ordered by private vs public. This is very messy and there are no settings that I have found to get this back.

**Comment by vetash** [comment]
I argue with that, any action in app took about 5-20 seconds. Even if you tap on input field, keyboard show up after 5 seconds.

**Comment by jivotnoto** [comment]
Hello, 

Me and my colleagues have issues with the latest Mattermost android app(not having this issue on the desktop app . 

Mattermost Version: 7.5.2
Database Schema Version: 95

Android app version 2.0.0 (beta) build 6000456 and now  im testing with the official 2.0.1 build 6000456

Android version - MIUI13.0.5 Android 12SP1A210812.016 

Have those issues on Samsung S21 android 13, Xaiomi Mi 9T android 12.1.1, Xiaomi MI 11  - android 12 skq1.211006.001, miui 13.0.7

Issue 1:
after message was received and i'm trying to open it directly via the notification bar it tooks long time to open the chat. 

issue 2: when changing chats it takes too much time to open the chat and sometimes when trying to sent messages. 

issue 3: application hangs sometimes when trying to attach file to channel or chat.

issue 4: when phone was locked after unlocking and opening notification to chat directly after typing the message the sent message button is unresponsive for more than 10-20 seconds

**Comment by enahum** [comment]
For the hangs and delays on some Android devices, I'm trying to work around it and find a solution based on the work that was done here https://github.com/facebook/react-native/pull/35967 that was suppose to mitigate this problem, but it seems that the fix is not complete as some devices are still affected.

We are seeing a lot of reports like this one

```
**Error**: `ApplicationNotResponding: Application Not Responding for at least 5000 ms.`
**Location**: `SpannableStringInternal.java:328`
**Request**: `android.text.SpannableStringInternal in getSpanFlags`
**Build**: `com.mattermost.rn@2.0.1+6000456`
```

**Comment by irrationalnumbers** [comment]
I was able to find out our server is running an older version and am asking the sys administrator to update it, though I'm not sure if they will. 

Along this line, I've noticed on mattermost's website that old versions of the server are available for download from the archive, but I have not been able to find old APK versions. Are they available somewhere officially?

**Comment by amyblais** [comment]
Older Mattermost app releases are here: https://github.com/mattermost/mattermost-mobile/releases.

**Comment by c0deright** [comment]
I might have fixed my issues by **disabling** Settings -> Advanced -> **Allow message drafts to sync with the server**. Please give it a try.

**Comment by vetash** [comment]
> I might have fixed my issues by **disabling** Settings -> Advanced -> **Allow message drafts to sync with the server**.
> 
> Please give it a try.

Unfortunately, this does not help. 

Xiaomi Redmi Note 11
Android 12
MIUI 13.0.2

**Comment by QldRobbo** [comment]
I have same issue, since the new mobile app update everything runs super super slow. Opening a channel takes 10-20s to refresh, trying to write a new message takes 5-10 seconds to open keyboard, trying to navigate around and actually have a conversation is almost impossible, it's pretty much unusable in it's current form.

I'm running app 2.1.0 on a server running 7.8.0, I'm using a pixel 7 pro. Our server has over 10 million messages, I'm in about 8 different teams and lots of channel, and the server is located in another country, roughly 400ms away.

**Comment by QldRobbo** [comment]
I just got a notification of a new message in a channel on my phone, I times how long it took for it to load up in the new message after tapping on the notification... The app loads almost instantly, it shows the previous message immediately, it took another 26 seconds for it to show the new message in the channel that it had already received the push notification for

**Comment by boombatower** [comment]
This is very consistent across multiple devices. Loads of reports on play store about this. If this was solved by cache clear the app should do it automatically on v2 upgrade and since it is not...should really put some effort into this or provide easy way to rollback. I've had a number of users push to move to something else as the mobile app is almost unusable and incredibly frustrating at the best of times now.

**Comment by mstgelais** [comment]
Just came here to add my voice. I manage a small Mattermost server for friends and family. Since V2 of the mobile app, we ALL experience these problems. I keep the server updated to the latest version, always. Many of us use Pixel phones of different models, if that information is in any way relevant.

Worst problems for me are the multiple app freezes when I try to send a message, and the many retries I often have to make. Both problems happen many times a day for my friends and I. Meanwhile, the web and desktop versions keep working great.

Aren't the developers experiencing these problems on a day to day basis? If they did, I guess this issue would be assigned at the very least. That's weird...

**Comment by boombatower** [comment]
Yeah, I don't understand it. This mottled my perception of mattermost. This seems to be have no priority and yet is ruining the experience for many. Textbook how to push users away ignore a major problem.

**Comment by enahum** [comment]
Is not being ignored, the main issue is caused by the technology we use and is being looked at, see https://github.com/facebook/react-native/issues/35936 and 
https://github.com/facebook/react-native/issues/35590

Sometimes issues can be a bit difficult to address and fix, I know it can be annoying and frustrating, hopefully you'll have a bit of patience.

Perhaps we can help the RN team here by collecting a list of devices/models and keyboards being used?

**Comment by mstgelais** [comment]
Thanks for the update @enahum. I'm a seasoned software developer myself and I wouldn't want to put unnecessary pressure. I figured two months and a half was showing "some" patience. Also, I totally get that this is free software, so I don't feel I'm entitled to any kind of results.

So... These problems are linked to React Native? That's good to know. Let's hope their team fixes them soon.

Now, just for the sake of conversation: if the first of these issues has been known since last December, and affects a lot of users, then why was Mattermost put out of beta / RC? I know pressure to release products can come from everywhere at once sometimes, but when the product has severe problems, releasing it won't help anyone (developers and users).

Again, thanks for taking some of your time to enlighten us on the situation.

**Comment by irrationalnumbers** [comment]
I have since installed the Android Mattermost v2.1 application including clearing data/cache.  Even with an older version of mattermost the application performed better.  Our admin recently installed the latest server version of 7.8.1 things seem to work much better.  This is limited to my device - I am not sure if different versions of Android are experiencing similar issues.

**Comment by mstgelais** [comment]
I'm gonna give it a try today @irrationalnumbers. I just cleared everything and it "fixed" a problem where some private channels appeared to be empty when in fact, they were not. As for the server, I'm my own sysadmin and I keep things pretty much up-to-date.

**Comment by mstgelais** [comment]
Well, two days later, I can sadly confirm that clearing the app's local data didn't fix anything. Some channels (but different ones) still appear to be empty, application hangs a lot when trying to edit a message, etc.

**Comment by boombatower** [comment]
Is there a location to download an official build of the 1.x series app?

**Comment by moussetc** [comment]
@boombatower 
> Is there a location to download an official build of the 1.x series app?

I dont know if its the best official source, but you can find unsigned APK on this repository, in the Assets of the last 1.x release https://github.com/mattermost/mattermost-mobile/releases/tag/v1.55.1

**Comment by enahum** [comment]
So the guys at the RN team merged a potential solution to their RC for the next release, I took the liberty to port their changes according to the changelog to a Test build of the mobile app, and have built it locally on my machine (this changes have not been added to the project as I needed to build react native from source).

The fix is around the Text inputs to avoid it from hanging, which seems to also be the cause of other non-responding gestures and so on.

The idea is to give this a try and report back in this thread (so I can also share this info with the RN team) hopefully this is fixed.

You can [download the apk from here](https://community.mattermost.com/files/6d9dockrctddj8i4t4b99aogqa/public?h=UD_pfS0_KGWuBG6BgplQBSItyt-u5e73Fd09YqBj_ZA) and then install it on your devices and see if the app does perform better.

Looking forward to the reports ;)

Thanks

**Comment by vetash** [comment]
Any updates on this issue? My team still have troubles with unresponsive UI from time to time.

**Comment by jivotnoto** [comment]
> Hello,
> 
> Me and my colleagues have issues with the latest Mattermost android app(not having this issue on the desktop app .
> 
> Mattermost Version: 7.5.2 Database Schema Version: 95
> 
> Android app version 2.0.0 (beta) build 6000456 and now im testing with the official 2.0.1 build 6000456
> 
> Android version - MIUI13.0.5 Android 12SP1A210812.016
> 
> Have those issues on Samsung S21 android 13, Xaiomi Mi 9T android 12.1.1, Xiaomi MI 11 - android 12 skq1.211006.001, miui 13.0.7
> 
> Issue 1: after message was received and i'm trying to open it directly via the notification bar it tooks long time to open the chat.
> 
> issue 2: when changing chats it takes too much time to open the chat and sometimes when trying to sent messages.
> 
> issue 3: application hangs sometimes when trying to attach file to channel or chat.
> 
> issue 4: when phone was locked after unlocking and opening notification to chat directly after typing the message the sent message button is unresponsive for more than 10-20 seconds

Issue still persist. Sometimes this happens when opening the android application, sometimes when attempting to reply to someone, last time i've attempted to share picture and after selecting the image it took ~30 minutes until i was able to press the send button or interact with the app. Having this issue for so much time is making people nervous, especially when you're paying for corporate license.

**Comment by irrationalnumbers** [comment]
From my side, our sys admin upgraded to Mattermost server 7.8.1 using MySQL database scheme version 101. Between the upgrade and reinstalling the latest release of the Mattermost apps, my issues have been resolved.

**Comment by jivotnoto** [comment]
> 

i forgot to mention that we have upgraded Mattermost server to latest available version with DB schema 105

**Comment by vetash** [comment]
Anyone have v1.55 apk? Release link https://releases.mattermost.com/mattermost-mobile/1.55.1/423/Mattermost-universal.apk is broken response with 403 error. :(

**Comment by larkox** [comment]
@vetash Any of the other links here should work: https://github.com/mattermost/mattermost-mobile/releases/tag/v1.55.0

**Comment by Luensche** [comment]
> So the guys at the RN team merged a potential solution to their RC for the next release, I took the liberty to port their changes according to the changelog to a Test build of the mobile app, and have built it locally on my machine (this changes have not been added to the project as I needed to build react native from source).
> 
> The fix is around the Text inputs to avoid it from hanging, which seems to also be the cause of other non-responding gestures and so on.
> 
> The idea is to give this a try and report back in this thread (so I can also share this info with the RN team) hopefully this is fixed.
> 
> You can [download the apk from here](https://community.mattermost.com/files/6d9dockrctddj8i4t4b99aogqa/public?h=UD_pfS0_KGWuBG6BgplQBSItyt-u5e73Fd09YqBj_ZA) and then install it on your devices and see if the app does perform better.
> 
> Looking forward to the reports ;)
> 
> Thanks

Is this fix already included in the public beta?

**Comment by ChristianGruen** [comment]
The app is very slow, composted to the web version. Is there any chance to get it faster, or would you recommend everyone to use the browser instead?

**Comment by vetash** [comment]
Seems like latest update fix all problems with performance.

**Comment by larkox** [comment]
According to @vetash, he is no longer seeing performance issues. @Luensche @ChristianGruen are you still seeing issues, or should I close this ticket?

**Comment by beliaev-maksim** [comment]
@larkox also confirm that it is fixed

**Comment by ChristianGruen** [comment]
@larkox Thanks for the reminder. The app has become faster again. It’s not as fast as the browser version, but definitely faster than with the previous version.

**Comment by vetash** [comment]
Its for me or latest update returned troubles with performance?

**Comment by vetash** [comment]
v2.6.0 messed up again. 2.5.1 have some updates that works perfect. @larkox can you reopen this issue? Or we must create new one?

**Comment by enahum** [comment]
@vetash have you reinstalled the app since? just want to make sure is cause of the changes in 2.6 as I cannot see anything of significance in the commits that could have an effect on the performance

**Comment by vetash** [comment]
@enahum 
On this phone, the first installed release was version 2.5.0. The update was successively carried out automatically through Google Play from 2.5.0 to 2.5.1 to 2.6.0.

After your hint that it might be caused by an old installation, I decided to reinstall the app - and for the past two weeks, everything has been working correctly.

However, this does not negate the fact that there was degradation.

Imagine a situation where you have hundreds of employees using Mattermost on their phones, and from release to release, they need to reinstall the app.
This is unacceptable.

I understand that it's open-source, and I could've helped the project by debugging the code and pushing a commit, but unfortunately, I'm not that advanced in mobile development.

@enahum 
It reminds me of the transition to version 2.0 on January 17th. After the 2.0 release, several issues were created describing performance problems. All this time, we had to use other messengers, which led to Mattermost no longer being the platform for corporate communication in our company. It's regrettable since much effort was put into integrating with the company's CRM systems and external services.

Again, I don't want to offend anyone, but it seems to me that testing mobile versions should be more thorough.

Perhaps it's worth adding some workaround in the mobile app, like "clear all data except authorization"?

It might also be beneficial to collect debug data from mobile apps for a more detailed analysis.

In any case, thank you for the app. I'll keep in mind that if any issues arise, I should start by reinstalling the application.

**Comment by enahum** [comment]
> @enahum 
> 
> On this phone, the first installed release was version 2.5.0. The update was successively carried out automatically through Google Play from 2.5.0 to 2.5.1 to 2.6.0.
> 
> 
> 
> After your hint that it might be caused by an old installation, I decided to reinstall the app - and for the past two weeks, everything has been working correctly.
> 
> 
> 
> However, this does not negate the fact that there was degradation.
> 
> 
> 
> Imagine a situation where you have hundreds of employees using Mattermost on their phones, and from release to release, they need to reinstall the app.
> 
> This is unacceptable.
> 
> 
> 
> I understand that it's open-source, and I could've helped the project by debugging the code and pushing a commit, but unfortunately, I'm not that advanced in mobile development.

I agree with you completely, hopefully it'll get better starting on 2.7 as we did add a cache and data auto clean up

**Comment by Cat-in-frill** [comment]
Just got here to say that unfortunately it still is not fixed.
Server: v7.8.9 
App: latest, e.g. v2.7
Android version: various, up to 13. 

All the same symptoms on different devices, that one can describe as "almost unresponsive application when changing chats or trying to type or trying to send message".

We're planning our upgrade to 8.1 soon, so I hope it could be something on server side...
