### ISSUE TITLE
[iOS] "Maximum call stack size exceeded" error

### ISSUE THREAD

**Issue by AzamServer** [mattermost/mattermost-mobile#7266]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-mobile/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed.

#### Summary
Getting an error saying "Maximum call stack size exceeded" when trying to edit/reply messages only on iOS app. Error then crashes edit/reply window.

### Environment Information (1)
  - Device Name: iPhone 11
  - OS Version: 16.5 Developer Beta
  - Mattermost App Version: 2.2.0 (Build 462)
  - Mattermost Server Version: 7.10.0 (Build .0)

### Environment Information (2)
  - Device Name: iPhone 13 mini
  - OS Version: 16.5 Developer Beta
  - Mattermost App Version: 2.2.0 (Build 462)
  - Mattermost Server Version: 7.10.0 (Build .0)

### Environment Information (3)
  - Device Name: iPhone 13 mini
  - OS Version: 16.4
  - Mattermost App Version: 2.2.0 (Build 462)
  - Mattermost Server Version: 7.10.0 (Build .0)

#### Steps to reproduce
Run Mattermost iOS app and try to edit/reply to messages. If that doesn't work, try making two iOS users edit/reply at the same time.

#### Expected behavior
Allow iOS user to reply/edit message without error appearing

#### Observed behavior (that appears unintentional)
Tried to edit/reply to message on iOS device, and got this error:
![Error Image](https://user-images.githubusercontent.com/78570129/229683585-ef183cc3-ffa7-4f4c-ae15-18529e817f16.PNG)

#### Possible fixes
N/A

**Comment by moussetc** [comment]
I have the same error message on Android
(Although the error stack is not the same)
Device Samsung S10e
Os Android 12, oneUI 4.1
App Version 2.2.0
Server  version 7.9.1
![Screenshot_20230408_163931_Mattermost](https://user-images.githubusercontent.com/8834237/232022668-c959f924-ad0b-43e0-a2e0-068ce52ad320.jpg)
![Screenshot_20230408_163939_Mattermost](https://user-images.githubusercontent.com/8834237/232022721-9d6d91b1-3546-4bd4-a275-81cd96c2efc9.jpg)
![Screenshot_20230408_163947_Mattermost](https://user-images.githubusercontent.com/8834237/232022773-c145460e-beaa-4c32-9d0a-6ccd715ba933.jpg)

**Comment by moussetc** [comment]
Hi! Any news on this issue? It happens very, very often when using the emoji picker, or when trying to edit a message.

**Comment by amyblais** [comment]
@enahum @larkox Was this fixed in v2.4, or not yet?

**Comment by larkox** [comment]
As far as I know, there has been nothing explicitly done for this bug, but other bug fixes may have solved the root issue. But not sure about that last part.

**Comment by enahum** [comment]
I wonder if there is anything specific that could cause this as I'm unable to reproduce either by editing a post or opening the emoji picker. I've tried on iOS and Android.

So it would be incredible if anyone can pinpoint a pattern or something specific to a channel / message

**Comment by AzamServer** [comment]
> I wonder if there is anything specific that could cause this as I'm unable to reproduce either by editing a post or opening the emoji picker. I've tried on iOS and Android.
> 
> 
> 
> So it would be incredible if anyone can pinpoint a pattern or something specific to a channel / message

I sometimes get the error when bringing up a pop up (long pressing a message/editing a message), but it usually happens when other people are active/typing. It may also be due to the fact that we have 20k+ messages in the channel we text in and we send 200+ messages every day. I also run the Mattermost server behind a Cloudflare Tunnel, so I wonder if that's causing the issue.

**Comment by AzamServer** [comment]
I can confirm that the error still exists on the latest beta of Mattermost (iOS v2.4.0 Build 471)

**Comment by larkox** [comment]
@AzamServer Are you open to send me the logs of your app to see if they bring some light into this? Join the Community Server and DM me them, and I will take a look. https://community.mattermost.com/core/messages/@daniel.espino-garcia

In order to get the logs, you should be able to got to settings, and hit the "Report a Problem" button.

**Comment by AzamServer** [comment]
> @AzamServer Are you open to send me the logs of your app to see if they bring some light into this? Join the Community Server and DM me them, and I will take a look. https://community.mattermost.com/core/messages/@daniel.espino-garcia
> 
> 
> 
> In order to get the logs, you should be able to got to settings, and hit the "Report a Problem" button.

Sure! I just created an account on the community Mattermost instance and will DM whenever I get and send the error.

**Comment by AzamServer** [comment]
> @AzamServer Are you open to send me the logs of your app to see if they bring some light into this? Join the Community Server and DM me them, and I will take a look. https://community.mattermost.com/core/messages/@daniel.espino-garcia
> 
> In order to get the logs, you should be able to got to settings, and hit the "Report a Problem" button.

Hi. I've gotten the error to popup on the iOS app v2.4.0 Build 471. I've DM'ed the logs to you on the community Mattermost instance.

**Comment by larkox** [comment]
@AzamServer Have you seen this issue again since build 472?

**Comment by moussetc** [comment]
(I muself haven't seen this issue in a while, thankfully :) )
